apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.labels.app}}-{{ .Values.labels.versionrelease}}-service"
spec:
  selector:
      app: {{ .Values.labels.app}}
      version: {{ .Values.labels.versionrelease }}
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80