name: ingress switch
on:
  workflow_dispatch:
        version:
        description: 'Updated version'
        required: true
        default: 'v'

jobs:
  ingress-switch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
            
      - name: Helm-Installation
        run: |
            sudo apt install openssl -y
            sudo snap install helm --classic

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1


      - name: Updating kubeconfig to connect to cluster
        run: |
           aws sts get-caller-identity
           aws eks --region ap-northeast-1 update-kubeconfig --name mycluster
           
      - name: public ingress switch
        run: |
           export oldversion=${{ inputs.version }}-2;
           kubectl patch ingress hello-world-ingress  -p "{\"spec\": {\"rules\": [{\"host\": \"*.amazonaws.com\",\"http\": {\"paths\": [{\"path\": \"/\",\"pathType\": \"Prefix\",\"backend\": {\"service\": {\"name\": \"hello-world-${{ inputs.version }}-service\",\"port\": {\"number\": 80}}}}]}}]}}"
           helm uninstall release-$oldversion
 